### PR TITLE
Give sport places higher rank

### PR DESCRIPTION
**Pull request by jbgriesner**
Do we want stadium and sport places appear ?
For instance the "Parc des Princes" in Paris:

## Before modification:
Parc des Princes before

## After modification:
Parc des Princes after

### CODE REVIEW

**Review by nlehuby — COMMENTED** [review]
stadium is now a duplicate.

Maybe remove sport, or put it more in the bottom

**Comment by jbgriesner** [comment]
done.

**Review by nlehuby — COMMENTED** [review]
to be tested again with last official openmaptiles version

**Comment by nlehuby** [comment]
does not seem necessary anymore with last OMT version:
parc des princes

**Pull request closed without merging**
